name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clear pylint cache
        run: rm -rf ~/.cache/pylint

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
          echo "export PYTHONPATH=$(pwd)" >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Verify PYTHONPATH
        run: echo "PYTHONPATH is set to: $PYTHONPATH"

      - name: Run pylint
        run: |
          pylint $(find . -name "*.py" | tr '\n' ' ')
